"""Bugfix Bill model

Revision ID: 41d461ffe570
Revises: bee3251de67f
Create Date: 2022-12-11 17:54:44.186214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d461ffe570'
down_revision = 'bee3251de67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', column_name='table', new_column_name='table_number')
    op.alter_column('bills', column_name='tip', new_column_name='tip_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
