"""add unique username

Revision ID: c15eb71d2d08
Revises: fb3bd1c1615d
Create Date: 2022-12-17 11:46:44.295139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15eb71d2d08'
down_revision = 'fb3bd1c1615d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'waiters', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waiters', type_='unique')
    # ### end Alembic commands ###
