"""Change password field length

Revision ID: fb3bd1c1615d
Revises: f6be41f940e5
Create Date: 2022-12-14 11:30:48.407705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3bd1c1615d'
down_revision = 'f6be41f940e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
